import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body
        className="__variable_4d318d __variable_ea5f4b antialiased" cz-shortcut-listen="true"
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
